-- run_test.py: invoking following command in '/workspaces/isaac_ros-dev/isaac_ros_nitros/isaac_ros_nitros':
 - /opt/ros/humble/bin/ament_flake8 --xunit-file /workspaces/isaac_ros-dev/build/isaac_ros_nitros/test_results/isaac_ros_nitros/flake8.xunit.xml


3 files checked
No problems found

Checked files:

* ./test/isaac_ros_nitros_test_pol.py
* ./test/isaac_ros_nitros_statistics_test_pol.py
* ./test/isaac_ros_nitros_multi_node_test_pol.py


-- run_test.py: return code 0
-- run_test.py: verify result file '/workspaces/isaac_ros-dev/build/isaac_ros_nitros/test_results/isaac_ros_nitros/flake8.xunit.xml'
